# Changes here will be overwritten by Copier. NEVER EDIT MANUALLY
# See: https://copier.readthedocs.io/en/stable/configuring/#the-copier-answersyml-file
_commit: v0.1.4
_src_path: gh:hexdoc-dev/hexdoc-mod-template
add_gitignore: true
add_vscode: true
advanced: true
author: Jempasam
base_book_url: https://jempasam.github.io/Hexlink/
book_id: hexlink:hexlinkbook
capitalize_platforms: false
default_branch: master
github_repo: Hexlink
gradle_minecraft_version_key: minecraft_version
gradle_mod_version_key: mod_version
mod_display_name: Hexlink
modid: hexlink
multiloader: false
plugin_ModPlugin_classname: HexlinkModPlugin
plugin_name: hexdoc-hexlink
plugin_pluggy_classname: HexlinkPlugin
plugin_root: doc
plugin_slug: hexdoc_hexlink
